export const missions = [
  {
    id: 1,
    name: "Patrol strefy A",
    status: "Aktywna",
    robot: "Robot-001",
    startedAt: "2024-06-17 08:30",
    completedAt: null,
  },
  {
    id: 2,
    name: "Inspekcja magazynu",
    status: "Zakończona",
    robot: "Robot-002",
    startedAt: "2024-06-17 07:15",
    completedAt: "2024-06-17 09:45",
  },
  {
    id: 3,
    name: "Transport materiałów",
    status: "W trakcie",
    robot: "Robot-003",
    startedAt: "2024-06-17 10:00",
    completedAt: null,
  },
  {
    id: 4,
    name: "Kontrola bezpieczeństwa",
    status: "Oczekuje",
    robot: "Robot-004",
    startedAt: null,
    completedAt: null,
  },
  {
    id: 5,
    name: "Czyszczenie strefy B",
    status: "Aktywna",
    robot: "Robot-005",
    startedAt: "2024-06-17 11:15",
    completedAt: null,
  },
  {
    id: 6,
    name: "Monitoring temperatury",
    status: "Zakończona",
    robot: "Robot-001",
    startedAt: "2024-06-17 06:00",
    completedAt: "2024-06-17 07:30",
  },
  {
    id: 7,
    name: "Dostawa części",
    status: "W trakcie",
    robot: "Robot-006",
    startedAt: "2024-06-17 09:45",
    completedAt: null,
  },
  {
    id: 8,
    name: "Skanowanie QR kodów",
    status: "Oczekuje",
    robot: "Robot-007",
    startedAt: null,
    completedAt: null,
  },
];
